from maxo.fsm import State

REG_NAME = State("reg_name")
REG_PHONE = State("reg_phone")
REG_CITY = State("reg_city")
EDIT = State("edit")
NO_CREATED_OBJECTS = State("no_created_objects")
OBJECT_SET_CITY = State("object_set_city")
OBJECT_SET_ADDRESS = State("object_set_address")
OBJECT_SET_DESCRIPTION = State("object_set_description")
OBJECT_LOAD_PHOTO = State("object_load_photo")
OBJECT_LOAD_DOCUMENTS = State("object_load_documents")
OBJECT_SET_PRICE = State("object_set_price")
OBJECT_CONFIRM = State("object_confirm")
SEARCH_ID = State("search_id")
SEARCH_QR = State("search_qr")