"""Place changed

Revision ID: 9501fb9489c9
Revises: abbf27c1cd0f
Create Date: 2026-09-28 11:03:43.366181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9501fb9489c9'
down_revision: Union[str, Sequence[str], None] = 'abbf27c1cd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('city', sa.String(), nullable=False))
    op.add_column('places', sa.Column('url_documents', sa.String(), nullable=False))
    op.drop_column('places', 'downloaded_documents')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'creation_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('places', sa.Column('downloaded_documents', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('places', 'url_documents')
    op.drop_column('places', 'city')
    # ### end Alembic commands ###
